### ISSUE TITLE
USER STORY: Filter products

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#10]
As a **Site User** I can **add a filter to the products** so that **I can find specific products I am looking for**.

## Acceptance criteria
- I can easily find buttons / links to help me filter products.
- I only see relevant products to the filter I have selected.
- I can remove or alter the filter easily.

## Tasks
- [x] Add buttons / links to products list page for the filters
- [x] Add logic to return filtered products
- [x] Render the products on products page
- [x] Add buttons / links to remove filter
