### ISSUE TITLE
USER STORY: Sort products

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#11]
As a **Site User** I can **sort products by name, price, category etc.** so that **I can find certain / similar products easier**.

## Acceptance criteria
- I can easily find a "sort" button / menu on the site.
- I can choose between relevant and helpful sorting methods.
- The products are sorted as expected when choosing a sort method.

## Tasks
- [x] Add button / menu to products list page for sorting products
- [x] Add logic to return sorted products
- [x] Render the sorted products on products page
