### ISSUE TITLE
USER STORY: Add products to cart

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#12]
As a **Site User** I can **add products to a cart** so that **I can save it and purchase more than one product at a time**.

## Acceptance criteria
- I can easily find an "add to cart" button on the product detail page.
- When I click it, my cart is updated to reflect my saved products.

## Tasks
- [x] Add "add to cart" button to product detail page
- [x] Add logic to add product to user session
- [x] Create cart to hold saved products
