### ISSUE TITLE
USER STORY: Cart details

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#13]
As a **Site User** I can **click on the cart** so that **I can view the products I have saved for purchase and my total cost**.

## Acceptance criteria
- I can easily find the cart icon in the upper right corner as expected.
- I can see all products in my cart on a separate page.
- I can see the product details of my saved items.
- I can see my subtotal and grand total for all products.

## Tasks
- [x] Add cart icon to upper right corner of the site
- [x] Create cart page with all products in cart rendered in a list
- [x] Add product details to each item
- [x] Add subtotal plus any additional charges as grand total
