### ISSUE TITLE
USER STORY: Edit cart items

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#15]
As a **Site User** I can **edit my saved items on the cart page** so that **I can change my cart content as I wish**.

## Acceptance criteria
- I can easily find an edit option on each product in my cart.
- I can increment / decrement product quantity straight from the cart page.
- The new total is reflected in my cart as I update product quantities.

## Tasks
- [x] Add input for incrementing / decrementing item quantity on each item in cart
- [x] Add logic for incrementing / decrementing item quantity
- [x] update total cost of product, subtotal and grand total each time the cart is edited
