### ISSUE TITLE
USER STORY: Delete cart items

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#16]
As a **Site User** I can **delete saved items on the cart page** so that **I can change my cart content as I wish**.

## Acceptance criteria
- I can easily find a delete option on each product in my cart.
- I can click delete and the item is removed from my cart.
- The new total is reflected in my cart as I delete product(s).

## Tasks
- [x] Add button / link to delete item on each item in cart
- [x] Add logic for deleting item
- [x] Update subtotal and grand total each time an item is deleted
