### ISSUE TITLE
USER STORY: User checkout

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#17]
As a **Site User** I can **checkout and pay for the products in my cart** so that **I can buy and receive my newly purchased products**.

## Acceptance criteria
- From my cart, I can easily find a checkout button / link
- When I click it, I am taken to a checkout page
- I can fill in my delivery and billing info (or have it autofill if I am signed in and have it saved).
- My order gets processed and I receive an order confirmation with all necessary info.

## Tasks
- [x] Add "checkout" button / link to cart page
- [x] Create models for orders and order items
- [x] Create checkout page with delivery / billing form
- [x] Set up Stripe API to handle payments and render stripe element on checkout page
- [x] Set up webhooks to handle unforeseen events when processing payments
