### ISSUE TITLE
USER STORY: Checkout details

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#18]
As a **Site User** I can **view details of my order on the checkout page** so that **I can make sure everything is correct before placing my order**.

## Acceptance criteria
- I can see all products I am about to buy and their information
- If I want to change my order I can easily go back to my cart OR delete / edit items from the checkout page
- I can see the exact amount I will be billed when placing my order

## Tasks
- [x] Render all products on the checkout page with all relevant info
- [x] Add button to go back to cart OR add edit / delete cart items options to checkout page
- [x] Add clear statement of the grand total to be charged to users card
