### ISSUE TITLE
USER STORY: Order confirmation

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#19]
As a **Site User** I can **have my order confirmed after a purchase** so that **I can be certain my payment was processed successfully**.

## Acceptance criteria
- After making a successful purchase, I am taken to an order confirmation page.
- I can view my order with all relevant info
- I will receive an order confirmation on my registered email address.

## Tasks
- [x] Create order confirmation page and redirect user after a successful purchase
- [x] Render complete order details
- [x] Configure SMTP to send automatic email confirmation to user
- [x] Add button / link to a relevant next step
