### ISSUE TITLE
USER STORY: Update account info

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#2]
As a **Signed In User** I can **view and update my information** so that **I can make sure the correct info is stored on me**.

## Acceptance criteria
- I can view my current information stored on the site.
- I can update my info to make sure my shipping address etc. is correct.

## Tasks
- [x] Expand built in user model with profile model
- [x] Create profile page with user information
- [x] Add form handling for updating information
