### ISSUE TITLE
USER STORY: Add products

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#20]
As a **Site admin** I can **add products to the site** so that **I can control the selection of products being sold**.

## Acceptance criteria
- I can easily find an "add product" button / link
- When I click it, I am taken to a page where I can fill in a form to add a product
- When I add a product, I can immediately find it on the site along with customers

## Tasks
- [x] Add "add product" link for site admins
- [x] Create new product page with a form for adding products
- [x] Add form handling to submit new products to database
