### ISSUE TITLE
USER STORY: Edit existing products

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#21]
As a **Site admin** I can **edit products on the site** so that **I can make sure the products being sold are correctly represented**.

## Acceptance criteria
- On the product detail page, I can easily find a link to edit products.
- When I click it, I am taken to a page where I can fill in a form to edit a product.
- When I edit a product, I can immediately see the changes to the product on the site along with customers.

## Tasks
- [x] Add "edit product" link for site admins on product detail page
- [x] Create edit product page with a form for editing products
- [x] Add form handling to submit edited products to database
