### ISSUE TITLE
USER STORY: Delete existing products

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#22]
As a **Site admin** I can **delete products on the site** so that **I can control the selection of products being sold**.

## Acceptance criteria
- On the product detail page, I can easily find a link to delete products.
- When I click it, I am asked if I am sure if I wish to delete the product, so I don't delete something by accident.
- When I delete a product, it is immediately removed from the site.

## Tasks
- [x] Add "delete product" link for site admins on product detail page
- [x] Add modal or separate page for confirmation
- [x] Delete product completely from database
