### ISSUE TITLE
USER STORY: User interaction confirmation

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#23]
As a **Site User** I can **expect confirmation on my interactions with the site** so that **my actions get confirmed**.

## Acceptance criteria
- I get confirmation when I for example create an account or add a product to my cart
- The messages are relevant and non intrusive on the UX.

## Tasks
- [x] Add messages logic to site
- [x] Create toasts for different scenarios of user interactions
- [x] render toasts when users interact with the site
