### ISSUE TITLE
USER STORY: Rate / review products

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#24]
As a **Site User** I can **rate / review products I have purchased** so that **I can share my product experience with other customers**.

## Acceptance criteria
- I can easily find an option to rate / review a product I have bought.
- When I leave a review, I can immediately see it reflected on the site.

## Tasks
- [x] Create review model
- [x] Add review form in product detail page
- [x] Add form handling to submit new reviews to database
