### ISSUE TITLE
USER STORY: Delete own review

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#27]
As a **site user** I can **delete my own review** so that **I can decide which of my own content is visible, and I can write a new review if I wish**.

## Acceptance criteria
- I can easily find a 'delete' link by my review
- When I click it, I am asked if I am sure if I wish to delete the review, so I don't delete something by accident.
- When I delete my review, it is immediately removed from the site.

## Tasks
- [x] Add "delete review" link for authors of review on product detail page
- [x] Add modal or separate page for confirmation
- [x] Delete review completely from database
