### ISSUE TITLE
USER STORY: Contact Form

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#28]
As a **Site User** I can **contact Gamers Ground** so that **I can ask questions or give feedback**.

## Acceptance criteria
- I can easily find a link / button for a contact page.
- I can fill in the form and, if I am signed in, my info will be prefilled.
- When I submit the form, I receive a copy of the inquiry to my email.

## Tasks
- [x] Create inquiry model
- [x] Create contact page and add inquiry form
- [x] Add form handling to save inquiries to database and send an email to admin and user
