### ISSUE TITLE
USER STORY: Delete account

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#3]
As a **Signed In User** I can **delete my account** so that **no information is stored on me**.

## Acceptance criteria
- I can find the "delete account" button on the profile page.
- I am asked if I am sure before deleting my account.
- I get redirected to the home page after deleting my account.

## Tasks
- [x] Add "delete account" button to user profile page
- [x] Add modal or separate page for confirmation
- [x] Delete user completely from database
