### ISSUE TITLE
USER STORY: Order history

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#4]
As a **Signed In User** I can **view previous order information** so that **I can see the details and make sure the orders are correct**.

## Acceptance criteria
- I can view a list of all previous orders.
- I can view a specific order on a separate page.

## Tasks
- [x] List order history on user profile page
- [x] Add link to each order
- [x] Create specific order details page
