### ISSUE TITLE
USER STORY: View products

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#6]
As a **Site User** I can **easily find and view products available** so that **I can browse products I may want to buy**.

## Acceptance criteria
- I can easily find all products without issue.
- I can see a short summary of the product, like price, name, picture etc. 

## Tasks
- [x] Create product model
- [x] Create products list page
- [x] Add a card for each product with vital info
