### ISSUE TITLE
USER STORY: Search products

### ISSUE THREAD

**Issue by LucasBehrendt** [LucasBehrendt/gamers-ground#9]
As a **Site User** I can **search for products using keywords** so that **I can find a specific product I have in mind**.

## Acceptance criteria
- I can easily find a search bar on the site.
- I can use keywords such as product name, description etc. to find products.
- Only relevant results are shown after searching.

## Tasks
- [x] Add search bar to top part of site
- [x] Add logic to return relevant products by name or description.
- [x] Render the products on products page
